<?php

declare(strict_types=1);

namespace App\Migrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260705062405 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE worksheet_submissions (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, response_text TEXT DEFAULT NULL, attachment_url VARCHAR(500) DEFAULT NULL, status VARCHAR(20) NOT NULL, score SMALLINT DEFAULT NULL, feedback TEXT DEFAULT NULL, submitted_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, graded_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, worksheet_id INT NOT NULL, student_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_212C33B42A915FFA ON worksheet_submissions (worksheet_id)');
        $this->addSql('CREATE INDEX IDX_212C33B4CB944F1A ON worksheet_submissions (student_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_worksheet_student ON worksheet_submissions (worksheet_id, student_id)');
        $this->addSql('CREATE TABLE worksheets (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, title VARCHAR(200) NOT NULL, track VARCHAR(20) NOT NULL, instructions TEXT DEFAULT NULL, attachment_url VARCHAR(500) DEFAULT NULL, total_marks SMALLINT DEFAULT 10 NOT NULL, due_date DATE DEFAULT NULL, approval_status VARCHAR(20) DEFAULT \'draft\' NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, topic_id INT NOT NULL, class_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_F74EE77D1F55203D ON worksheets (topic_id)');
        $this->addSql('CREATE INDEX IDX_F74EE77DEA000B10 ON worksheets (class_id)');
        $this->addSql('ALTER TABLE worksheet_submissions ADD CONSTRAINT FK_212C33B42A915FFA FOREIGN KEY (worksheet_id) REFERENCES worksheets (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE worksheet_submissions ADD CONSTRAINT FK_212C33B4CB944F1A FOREIGN KEY (student_id) REFERENCES users (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE worksheets ADD CONSTRAINT FK_F74EE77D1F55203D FOREIGN KEY (topic_id) REFERENCES topics (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE worksheets ADD CONSTRAINT FK_F74EE77DEA000B10 FOREIGN KEY (class_id) REFERENCES school_classes (id) ON DELETE SET NULL NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE worksheet_submissions DROP CONSTRAINT FK_212C33B42A915FFA');
        $this->addSql('ALTER TABLE worksheet_submissions DROP CONSTRAINT FK_212C33B4CB944F1A');
        $this->addSql('ALTER TABLE worksheets DROP CONSTRAINT FK_F74EE77D1F55203D');
        $this->addSql('ALTER TABLE worksheets DROP CONSTRAINT FK_F74EE77DEA000B10');
        $this->addSql('DROP TABLE worksheet_submissions');
        $this->addSql('DROP TABLE worksheets');
    }
}
