<?php

declare(strict_types=1);

namespace App\Migrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260705173850 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE safeguarding_cases (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, category VARCHAR(30) NOT NULL, summary VARCHAR(200) NOT NULL, details TEXT DEFAULT NULL, status VARCHAR(20) NOT NULL, outcome TEXT DEFAULT NULL, closed_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, student_id INT DEFAULT NULL, reported_by INT DEFAULT NULL, institution_id INT DEFAULT NULL, handled_by INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_74F039A9CB944F1A ON safeguarding_cases (student_id)');
        $this->addSql('CREATE INDEX IDX_74F039A9144F5BA4 ON safeguarding_cases (reported_by)');
        $this->addSql('CREATE INDEX IDX_74F039A910405986 ON safeguarding_cases (institution_id)');
        $this->addSql('CREATE INDEX IDX_74F039A953689D12 ON safeguarding_cases (handled_by)');
        $this->addSql('CREATE INDEX idx_safeguarding_status ON safeguarding_cases (status)');
        $this->addSql('ALTER TABLE safeguarding_cases ADD CONSTRAINT FK_74F039A9CB944F1A FOREIGN KEY (student_id) REFERENCES users (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE safeguarding_cases ADD CONSTRAINT FK_74F039A9144F5BA4 FOREIGN KEY (reported_by) REFERENCES users (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE safeguarding_cases ADD CONSTRAINT FK_74F039A910405986 FOREIGN KEY (institution_id) REFERENCES institutions (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE safeguarding_cases ADD CONSTRAINT FK_74F039A953689D12 FOREIGN KEY (handled_by) REFERENCES users (id) ON DELETE SET NULL NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE safeguarding_cases DROP CONSTRAINT FK_74F039A9CB944F1A');
        $this->addSql('ALTER TABLE safeguarding_cases DROP CONSTRAINT FK_74F039A9144F5BA4');
        $this->addSql('ALTER TABLE safeguarding_cases DROP CONSTRAINT FK_74F039A910405986');
        $this->addSql('ALTER TABLE safeguarding_cases DROP CONSTRAINT FK_74F039A953689D12');
        $this->addSql('DROP TABLE safeguarding_cases');
    }
}
