<?php

declare(strict_types=1);

namespace App\Migrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260705124920 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE topic_progress (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, lesson_viewed BOOLEAN DEFAULT false NOT NULL, lesson_viewed_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, topic_id INT NOT NULL, student_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_D4307F401F55203D ON topic_progress (topic_id)');
        $this->addSql('CREATE INDEX IDX_D4307F40CB944F1A ON topic_progress (student_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_topic_student_progress ON topic_progress (topic_id, student_id)');
        $this->addSql('ALTER TABLE topic_progress ADD CONSTRAINT FK_D4307F401F55203D FOREIGN KEY (topic_id) REFERENCES topics (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE topic_progress ADD CONSTRAINT FK_D4307F40CB944F1A FOREIGN KEY (student_id) REFERENCES users (id) ON DELETE CASCADE NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE topic_progress DROP CONSTRAINT FK_D4307F401F55203D');
        $this->addSql('ALTER TABLE topic_progress DROP CONSTRAINT FK_D4307F40CB944F1A');
        $this->addSql('DROP TABLE topic_progress');
    }
}
