<?php

declare(strict_types=1);

namespace App\Migrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260705004059 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE questions (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, type VARCHAR(20) NOT NULL, track VARCHAR(20) NOT NULL, difficulty VARCHAR(10) NOT NULL, stem TEXT NOT NULL, options JSON DEFAULT NULL, correct_answer JSON DEFAULT NULL, explanation TEXT DEFAULT NULL, marks SMALLINT DEFAULT 1 NOT NULL, answer_validated BOOLEAN DEFAULT false NOT NULL, approval_status VARCHAR(20) DEFAULT \'draft\' NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, topic_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_8ADC54D51F55203D ON questions (topic_id)');
        $this->addSql('ALTER TABLE questions ADD CONSTRAINT FK_8ADC54D51F55203D FOREIGN KEY (topic_id) REFERENCES topics (id) ON DELETE CASCADE NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE questions DROP CONSTRAINT FK_8ADC54D51F55203D');
        $this->addSql('DROP TABLE questions');
    }
}
