<?php

declare(strict_types=1);

namespace App\Migrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260705194314 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE content_packages (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(160) NOT NULL, package_type VARCHAR(30) NOT NULL, description TEXT DEFAULT NULL, subject_area VARCHAR(120) DEFAULT NULL, grade_level VARCHAR(60) DEFAULT NULL, price_kobo INT DEFAULT 0 NOT NULL, duration_months INT DEFAULT NULL, is_active BOOLEAN DEFAULT true NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE content_package_resources (contentpackage_id INT NOT NULL, contentresource_id INT NOT NULL, PRIMARY KEY (contentpackage_id, contentresource_id))');
        $this->addSql('CREATE INDEX IDX_16838924893742E1 ON content_package_resources (contentpackage_id)');
        $this->addSql('CREATE INDEX IDX_168389247340DBAF ON content_package_resources (contentresource_id)');
        $this->addSql('CREATE TABLE content_resources (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, title VARCHAR(200) NOT NULL, content_type VARCHAR(20) NOT NULL, subject_area VARCHAR(120) DEFAULT NULL, grade_level VARCHAR(60) DEFAULT NULL, description TEXT DEFAULT NULL, difficulty_level VARCHAR(20) DEFAULT NULL, tags JSON DEFAULT NULL, is_premium BOOLEAN DEFAULT false NOT NULL, file_url VARCHAR(500) DEFAULT NULL, file_name VARCHAR(255) DEFAULT NULL, file_size INT DEFAULT NULL, source VARCHAR(200) DEFAULT NULL, licence VARCHAR(20) NOT NULL, licence_status VARCHAR(20) NOT NULL, takedown_reason TEXT DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, created_by INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_DF81A3ADDE12AB56 ON content_resources (created_by)');
        $this->addSql('ALTER TABLE content_package_resources ADD CONSTRAINT FK_16838924893742E1 FOREIGN KEY (contentpackage_id) REFERENCES content_packages (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE content_package_resources ADD CONSTRAINT FK_168389247340DBAF FOREIGN KEY (contentresource_id) REFERENCES content_resources (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE content_resources ADD CONSTRAINT FK_DF81A3ADDE12AB56 FOREIGN KEY (created_by) REFERENCES users (id) ON DELETE SET NULL NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE content_package_resources DROP CONSTRAINT FK_16838924893742E1');
        $this->addSql('ALTER TABLE content_package_resources DROP CONSTRAINT FK_168389247340DBAF');
        $this->addSql('ALTER TABLE content_resources DROP CONSTRAINT FK_DF81A3ADDE12AB56');
        $this->addSql('DROP TABLE content_packages');
        $this->addSql('DROP TABLE content_package_resources');
        $this->addSql('DROP TABLE content_resources');
    }
}
