<?php

declare(strict_types=1);

namespace App\Migrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260705004536 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE assessment_questions (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, position SMALLINT DEFAULT 0 NOT NULL, marks SMALLINT DEFAULT NULL, assessment_id INT NOT NULL, question_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_58ADA739DD3DD5F1 ON assessment_questions (assessment_id)');
        $this->addSql('CREATE INDEX IDX_58ADA7391E27F6BF ON assessment_questions (question_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_assessment_question ON assessment_questions (assessment_id, question_id)');
        $this->addSql('CREATE TABLE assessments (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, title VARCHAR(200) NOT NULL, type VARCHAR(20) NOT NULL, track VARCHAR(20) NOT NULL, duration_minutes SMALLINT DEFAULT NULL, pass_mark SMALLINT DEFAULT 50 NOT NULL, instructions TEXT DEFAULT NULL, approval_status VARCHAR(20) DEFAULT \'draft\' NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, subject_id INT NOT NULL, topic_id INT DEFAULT NULL, class_id INT DEFAULT NULL, term_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_4BFCEC0A23EDC87 ON assessments (subject_id)');
        $this->addSql('CREATE INDEX IDX_4BFCEC0A1F55203D ON assessments (topic_id)');
        $this->addSql('CREATE INDEX IDX_4BFCEC0AEA000B10 ON assessments (class_id)');
        $this->addSql('CREATE INDEX IDX_4BFCEC0AE2C35FC ON assessments (term_id)');
        $this->addSql('ALTER TABLE assessment_questions ADD CONSTRAINT FK_58ADA739DD3DD5F1 FOREIGN KEY (assessment_id) REFERENCES assessments (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE assessment_questions ADD CONSTRAINT FK_58ADA7391E27F6BF FOREIGN KEY (question_id) REFERENCES questions (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE assessments ADD CONSTRAINT FK_4BFCEC0A23EDC87 FOREIGN KEY (subject_id) REFERENCES subjects (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE assessments ADD CONSTRAINT FK_4BFCEC0A1F55203D FOREIGN KEY (topic_id) REFERENCES topics (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE assessments ADD CONSTRAINT FK_4BFCEC0AEA000B10 FOREIGN KEY (class_id) REFERENCES school_classes (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE assessments ADD CONSTRAINT FK_4BFCEC0AE2C35FC FOREIGN KEY (term_id) REFERENCES terms (id) ON DELETE SET NULL NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE assessment_questions DROP CONSTRAINT FK_58ADA739DD3DD5F1');
        $this->addSql('ALTER TABLE assessment_questions DROP CONSTRAINT FK_58ADA7391E27F6BF');
        $this->addSql('ALTER TABLE assessments DROP CONSTRAINT FK_4BFCEC0A23EDC87');
        $this->addSql('ALTER TABLE assessments DROP CONSTRAINT FK_4BFCEC0A1F55203D');
        $this->addSql('ALTER TABLE assessments DROP CONSTRAINT FK_4BFCEC0AEA000B10');
        $this->addSql('ALTER TABLE assessments DROP CONSTRAINT FK_4BFCEC0AE2C35FC');
        $this->addSql('DROP TABLE assessment_questions');
        $this->addSql('DROP TABLE assessments');
    }
}
