<?php

declare(strict_types=1);

namespace App\Migrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260704211513 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE audit_logs (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, user_id INT DEFAULT NULL, institution_id INT DEFAULT NULL, action_type VARCHAR(100) NOT NULL, object_type VARCHAR(100) DEFAULT NULL, object_id VARCHAR(100) DEFAULT NULL, old_value JSON DEFAULT NULL, new_value JSON DEFAULT NULL, ip_device VARCHAR(255) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_audit_user ON audit_logs (user_id)');
        $this->addSql('CREATE INDEX idx_audit_object ON audit_logs (object_type, object_id)');
        $this->addSql('CREATE TABLE institutions (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, type VARCHAR(50) DEFAULT \'school\' NOT NULL, address TEXT DEFAULT NULL, logo_url VARCHAR(1024) DEFAULT NULL, branding JSON DEFAULT NULL, admin_contact JSON DEFAULT NULL, subscription_id INT DEFAULT NULL, assigned_package_id INT DEFAULT NULL, status VARCHAR(30) DEFAULT \'active\' NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE permissions (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, code VARCHAR(100) NOT NULL, description VARCHAR(255) DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_2DEDCC6F77153098 ON permissions (code)');
        $this->addSql('CREATE TABLE role_permissions (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, permission_code VARCHAR(100) NOT NULL, can_view BOOLEAN DEFAULT false NOT NULL, can_create BOOLEAN DEFAULT false NOT NULL, can_edit BOOLEAN DEFAULT false NOT NULL, can_approve BOOLEAN DEFAULT false NOT NULL, can_export BOOLEAN DEFAULT false NOT NULL, can_delete BOOLEAN DEFAULT false NOT NULL, scope VARCHAR(20) DEFAULT \'school\' NOT NULL, role_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_1FBA94E6D60322AC ON role_permissions (role_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_role_permission ON role_permissions (role_id, permission_code)');
        $this->addSql('CREATE TABLE roles (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, code VARCHAR(50) NOT NULL, name VARCHAR(100) NOT NULL, scope VARCHAR(20) DEFAULT \'school\' NOT NULL, is_system BOOLEAN DEFAULT false NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_B63E2EC777153098 ON roles (code)');
        $this->addSql('CREATE TABLE users (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, email VARCHAR(190) NOT NULL, password_hash VARCHAR(255) NOT NULL, first_name VARCHAR(100) NOT NULL, last_name VARCHAR(100) NOT NULL, phone VARCHAR(30) DEFAULT NULL, profile_image_url VARCHAR(1024) DEFAULT NULL, status VARCHAR(30) DEFAULT \'active\' NOT NULL, last_login TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, role_id INT NOT NULL, institution_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_1483A5E9E7927C74 ON users (email)');
        $this->addSql('CREATE INDEX IDX_1483A5E9D60322AC ON users (role_id)');
        $this->addSql('CREATE INDEX IDX_1483A5E910405986 ON users (institution_id)');
        $this->addSql('ALTER TABLE role_permissions ADD CONSTRAINT FK_1FBA94E6D60322AC FOREIGN KEY (role_id) REFERENCES roles (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE users ADD CONSTRAINT FK_1483A5E9D60322AC FOREIGN KEY (role_id) REFERENCES roles (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE users ADD CONSTRAINT FK_1483A5E910405986 FOREIGN KEY (institution_id) REFERENCES institutions (id) ON DELETE SET NULL NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE role_permissions DROP CONSTRAINT FK_1FBA94E6D60322AC');
        $this->addSql('ALTER TABLE users DROP CONSTRAINT FK_1483A5E9D60322AC');
        $this->addSql('ALTER TABLE users DROP CONSTRAINT FK_1483A5E910405986');
        $this->addSql('DROP TABLE audit_logs');
        $this->addSql('DROP TABLE institutions');
        $this->addSql('DROP TABLE permissions');
        $this->addSql('DROP TABLE role_permissions');
        $this->addSql('DROP TABLE roles');
        $this->addSql('DROP TABLE users');
    }
}
