<?php

declare(strict_types=1);

namespace App\Migrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260705075703 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE live_class_attendance (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, joined_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, live_class_id INT NOT NULL, student_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_9F7DC52E2D567EE4 ON live_class_attendance (live_class_id)');
        $this->addSql('CREATE INDEX IDX_9F7DC52ECB944F1A ON live_class_attendance (student_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_liveclass_student ON live_class_attendance (live_class_id, student_id)');
        $this->addSql('CREATE TABLE live_classes (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, title VARCHAR(200) NOT NULL, scheduled_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, duration_minutes SMALLINT DEFAULT 45 NOT NULL, room_name VARCHAR(200) DEFAULT NULL, room_url VARCHAR(500) DEFAULT NULL, status VARCHAR(20) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, subject_id INT NOT NULL, class_id INT DEFAULT NULL, topic_id INT DEFAULT NULL, host_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_83303EBE23EDC87 ON live_classes (subject_id)');
        $this->addSql('CREATE INDEX IDX_83303EBEEA000B10 ON live_classes (class_id)');
        $this->addSql('CREATE INDEX IDX_83303EBE1F55203D ON live_classes (topic_id)');
        $this->addSql('CREATE INDEX IDX_83303EBE1FB8D185 ON live_classes (host_id)');
        $this->addSql('ALTER TABLE live_class_attendance ADD CONSTRAINT FK_9F7DC52E2D567EE4 FOREIGN KEY (live_class_id) REFERENCES live_classes (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE live_class_attendance ADD CONSTRAINT FK_9F7DC52ECB944F1A FOREIGN KEY (student_id) REFERENCES users (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE live_classes ADD CONSTRAINT FK_83303EBE23EDC87 FOREIGN KEY (subject_id) REFERENCES subjects (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE live_classes ADD CONSTRAINT FK_83303EBEEA000B10 FOREIGN KEY (class_id) REFERENCES school_classes (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE live_classes ADD CONSTRAINT FK_83303EBE1F55203D FOREIGN KEY (topic_id) REFERENCES topics (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE live_classes ADD CONSTRAINT FK_83303EBE1FB8D185 FOREIGN KEY (host_id) REFERENCES users (id) ON DELETE SET NULL NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE live_class_attendance DROP CONSTRAINT FK_9F7DC52E2D567EE4');
        $this->addSql('ALTER TABLE live_class_attendance DROP CONSTRAINT FK_9F7DC52ECB944F1A');
        $this->addSql('ALTER TABLE live_classes DROP CONSTRAINT FK_83303EBE23EDC87');
        $this->addSql('ALTER TABLE live_classes DROP CONSTRAINT FK_83303EBEEA000B10');
        $this->addSql('ALTER TABLE live_classes DROP CONSTRAINT FK_83303EBE1F55203D');
        $this->addSql('ALTER TABLE live_classes DROP CONSTRAINT FK_83303EBE1FB8D185');
        $this->addSql('DROP TABLE live_class_attendance');
        $this->addSql('DROP TABLE live_classes');
    }
}
