<?php

declare(strict_types=1);

namespace App\Migrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260705065855 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE portfolio_entries (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, title VARCHAR(200) NOT NULL, description TEXT NOT NULL, evidence_url VARCHAR(500) DEFAULT NULL, status VARCHAR(20) NOT NULL, competency_rating VARCHAR(20) DEFAULT NULL, reviewer_feedback TEXT DEFAULT NULL, submitted_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, reviewed_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, topic_id INT NOT NULL, student_id INT NOT NULL, reviewed_by INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_7B4D9C0B1F55203D ON portfolio_entries (topic_id)');
        $this->addSql('CREATE INDEX IDX_7B4D9C0BCB944F1A ON portfolio_entries (student_id)');
        $this->addSql('CREATE INDEX IDX_7B4D9C0B85D7FB47 ON portfolio_entries (reviewed_by)');
        $this->addSql('ALTER TABLE portfolio_entries ADD CONSTRAINT FK_7B4D9C0B1F55203D FOREIGN KEY (topic_id) REFERENCES topics (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE portfolio_entries ADD CONSTRAINT FK_7B4D9C0BCB944F1A FOREIGN KEY (student_id) REFERENCES users (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE portfolio_entries ADD CONSTRAINT FK_7B4D9C0B85D7FB47 FOREIGN KEY (reviewed_by) REFERENCES users (id) ON DELETE SET NULL NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE portfolio_entries DROP CONSTRAINT FK_7B4D9C0B1F55203D');
        $this->addSql('ALTER TABLE portfolio_entries DROP CONSTRAINT FK_7B4D9C0BCB944F1A');
        $this->addSql('ALTER TABLE portfolio_entries DROP CONSTRAINT FK_7B4D9C0B85D7FB47');
        $this->addSql('DROP TABLE portfolio_entries');
    }
}
