<?php

declare(strict_types=1);

namespace App\Migrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260704223519 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE enrollments (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, enrollment_date DATE DEFAULT NULL, status VARCHAR(20) DEFAULT \'active\' NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, student_id INT NOT NULL, class_id INT NOT NULL, session_id INT DEFAULT NULL, term_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_CCD8C132CB944F1A ON enrollments (student_id)');
        $this->addSql('CREATE INDEX IDX_CCD8C132EA000B10 ON enrollments (class_id)');
        $this->addSql('CREATE INDEX IDX_CCD8C132613FECDF ON enrollments (session_id)');
        $this->addSql('CREATE INDEX IDX_CCD8C132E2C35FC ON enrollments (term_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_student_class ON enrollments (student_id, class_id)');
        $this->addSql('ALTER TABLE enrollments ADD CONSTRAINT FK_CCD8C132CB944F1A FOREIGN KEY (student_id) REFERENCES users (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE enrollments ADD CONSTRAINT FK_CCD8C132EA000B10 FOREIGN KEY (class_id) REFERENCES school_classes (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE enrollments ADD CONSTRAINT FK_CCD8C132613FECDF FOREIGN KEY (session_id) REFERENCES academic_sessions (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE enrollments ADD CONSTRAINT FK_CCD8C132E2C35FC FOREIGN KEY (term_id) REFERENCES terms (id) ON DELETE SET NULL NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE enrollments DROP CONSTRAINT FK_CCD8C132CB944F1A');
        $this->addSql('ALTER TABLE enrollments DROP CONSTRAINT FK_CCD8C132EA000B10');
        $this->addSql('ALTER TABLE enrollments DROP CONSTRAINT FK_CCD8C132613FECDF');
        $this->addSql('ALTER TABLE enrollments DROP CONSTRAINT FK_CCD8C132E2C35FC');
        $this->addSql('DROP TABLE enrollments');
    }
}
