<?php

declare(strict_types=1);

namespace App\Migrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260705230903 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE student_topic_notes (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, body TEXT NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, student_id INT NOT NULL, topic_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_6DC807EDCB944F1A ON student_topic_notes (student_id)');
        $this->addSql('CREATE INDEX IDX_6DC807ED1F55203D ON student_topic_notes (topic_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_student_topic_note ON student_topic_notes (student_id, topic_id)');
        $this->addSql('ALTER TABLE student_topic_notes ADD CONSTRAINT FK_6DC807EDCB944F1A FOREIGN KEY (student_id) REFERENCES users (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE student_topic_notes ADD CONSTRAINT FK_6DC807ED1F55203D FOREIGN KEY (topic_id) REFERENCES topics (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE topic_delivery_packs ADD media JSON DEFAULT NULL');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE student_topic_notes DROP CONSTRAINT FK_6DC807EDCB944F1A');
        $this->addSql('ALTER TABLE student_topic_notes DROP CONSTRAINT FK_6DC807ED1F55203D');
        $this->addSql('DROP TABLE student_topic_notes');
        $this->addSql('ALTER TABLE topic_delivery_packs DROP media');
    }
}
