<?php

declare(strict_types=1);

namespace App\Migrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260705012730 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE assessment_attempts (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, status VARCHAR(20) NOT NULL, track VARCHAR(20) NOT NULL, total_marks SMALLINT DEFAULT 0 NOT NULL, score SMALLINT DEFAULT NULL, percentage DOUBLE PRECISION DEFAULT NULL, passed BOOLEAN DEFAULT NULL, started_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, submitted_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, assessment_id INT NOT NULL, student_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_C3B1F642DD3DD5F1 ON assessment_attempts (assessment_id)');
        $this->addSql('CREATE INDEX IDX_C3B1F642CB944F1A ON assessment_attempts (student_id)');
        $this->addSql('CREATE TABLE attempt_answers (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, response JSON DEFAULT NULL, is_correct BOOLEAN DEFAULT NULL, marks_awarded SMALLINT DEFAULT 0 NOT NULL, attempt_id INT NOT NULL, question_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_949598D4B191BE6B ON attempt_answers (attempt_id)');
        $this->addSql('CREATE INDEX IDX_949598D41E27F6BF ON attempt_answers (question_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_attempt_question ON attempt_answers (attempt_id, question_id)');
        $this->addSql('ALTER TABLE assessment_attempts ADD CONSTRAINT FK_C3B1F642DD3DD5F1 FOREIGN KEY (assessment_id) REFERENCES assessments (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE assessment_attempts ADD CONSTRAINT FK_C3B1F642CB944F1A FOREIGN KEY (student_id) REFERENCES users (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE attempt_answers ADD CONSTRAINT FK_949598D4B191BE6B FOREIGN KEY (attempt_id) REFERENCES assessment_attempts (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE attempt_answers ADD CONSTRAINT FK_949598D41E27F6BF FOREIGN KEY (question_id) REFERENCES questions (id) ON DELETE CASCADE NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE assessment_attempts DROP CONSTRAINT FK_C3B1F642DD3DD5F1');
        $this->addSql('ALTER TABLE assessment_attempts DROP CONSTRAINT FK_C3B1F642CB944F1A');
        $this->addSql('ALTER TABLE attempt_answers DROP CONSTRAINT FK_949598D4B191BE6B');
        $this->addSql('ALTER TABLE attempt_answers DROP CONSTRAINT FK_949598D41E27F6BF');
        $this->addSql('DROP TABLE assessment_attempts');
        $this->addSql('DROP TABLE attempt_answers');
    }
}
