<?php

declare(strict_types=1);

namespace App\Migrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260705195430 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE support_messages (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, body TEXT NOT NULL, is_staff BOOLEAN DEFAULT false NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, ticket_id INT NOT NULL, author_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_6FB495A9700047D2 ON support_messages (ticket_id)');
        $this->addSql('CREATE INDEX IDX_6FB495A9F675F31B ON support_messages (author_id)');
        $this->addSql('CREATE TABLE support_tickets (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, reference VARCHAR(30) NOT NULL, subject VARCHAR(200) NOT NULL, category VARCHAR(20) NOT NULL, priority VARCHAR(20) NOT NULL, status VARCHAR(20) NOT NULL, escalated BOOLEAN DEFAULT false NOT NULL, first_response_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, resolved_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, institution_id INT DEFAULT NULL, created_by INT NOT NULL, assigned_to INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_E9739508AEA34913 ON support_tickets (reference)');
        $this->addSql('CREATE INDEX IDX_E973950810405986 ON support_tickets (institution_id)');
        $this->addSql('CREATE INDEX IDX_E9739508DE12AB56 ON support_tickets (created_by)');
        $this->addSql('CREATE INDEX IDX_E973950889EEAF91 ON support_tickets (assigned_to)');
        $this->addSql('ALTER TABLE support_messages ADD CONSTRAINT FK_6FB495A9700047D2 FOREIGN KEY (ticket_id) REFERENCES support_tickets (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE support_messages ADD CONSTRAINT FK_6FB495A9F675F31B FOREIGN KEY (author_id) REFERENCES users (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE support_tickets ADD CONSTRAINT FK_E973950810405986 FOREIGN KEY (institution_id) REFERENCES institutions (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE support_tickets ADD CONSTRAINT FK_E9739508DE12AB56 FOREIGN KEY (created_by) REFERENCES users (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE support_tickets ADD CONSTRAINT FK_E973950889EEAF91 FOREIGN KEY (assigned_to) REFERENCES users (id) ON DELETE SET NULL NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE support_messages DROP CONSTRAINT FK_6FB495A9700047D2');
        $this->addSql('ALTER TABLE support_messages DROP CONSTRAINT FK_6FB495A9F675F31B');
        $this->addSql('ALTER TABLE support_tickets DROP CONSTRAINT FK_E973950810405986');
        $this->addSql('ALTER TABLE support_tickets DROP CONSTRAINT FK_E9739508DE12AB56');
        $this->addSql('ALTER TABLE support_tickets DROP CONSTRAINT FK_E973950889EEAF91');
        $this->addSql('DROP TABLE support_messages');
        $this->addSql('DROP TABLE support_tickets');
    }
}
