<?php

declare(strict_types=1);

namespace App\Migrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260705215909 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE catalog_subjects (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(120) NOT NULL, code VARCHAR(30) NOT NULL, description TEXT DEFAULT NULL, curriculum VARCHAR(60) DEFAULT NULL, is_active BOOLEAN DEFAULT true NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_99F2470977153098 ON catalog_subjects (code)');
        $this->addSql('ALTER TABLE content_packages ADD catalog_subject_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE content_packages ADD CONSTRAINT FK_C9022A48B7142E5C FOREIGN KEY (catalog_subject_id) REFERENCES catalog_subjects (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('CREATE INDEX IDX_C9022A48B7142E5C ON content_packages (catalog_subject_id)');
        $this->addSql('ALTER TABLE subjects ADD catalog_subject_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE subjects ADD CONSTRAINT FK_AB259917B7142E5C FOREIGN KEY (catalog_subject_id) REFERENCES catalog_subjects (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('CREATE INDEX IDX_AB259917B7142E5C ON subjects (catalog_subject_id)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('DROP TABLE catalog_subjects');
        $this->addSql('ALTER TABLE content_packages DROP CONSTRAINT FK_C9022A48B7142E5C');
        $this->addSql('DROP INDEX IDX_C9022A48B7142E5C');
        $this->addSql('ALTER TABLE content_packages DROP catalog_subject_id');
        $this->addSql('ALTER TABLE subjects DROP CONSTRAINT FK_AB259917B7142E5C');
        $this->addSql('DROP INDEX IDX_AB259917B7142E5C');
        $this->addSql('ALTER TABLE subjects DROP catalog_subject_id');
    }
}
