<?php

declare(strict_types=1);

namespace App\Migrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260705073013 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE feedback_notes (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, type VARCHAR(20) NOT NULL, message TEXT NOT NULL, acknowledged BOOLEAN DEFAULT false NOT NULL, acknowledged_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, student_id INT NOT NULL, author_id INT DEFAULT NULL, topic_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_95BA3FE9CB944F1A ON feedback_notes (student_id)');
        $this->addSql('CREATE INDEX IDX_95BA3FE9F675F31B ON feedback_notes (author_id)');
        $this->addSql('CREATE INDEX IDX_95BA3FE91F55203D ON feedback_notes (topic_id)');
        $this->addSql('ALTER TABLE feedback_notes ADD CONSTRAINT FK_95BA3FE9CB944F1A FOREIGN KEY (student_id) REFERENCES users (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE feedback_notes ADD CONSTRAINT FK_95BA3FE9F675F31B FOREIGN KEY (author_id) REFERENCES users (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE feedback_notes ADD CONSTRAINT FK_95BA3FE91F55203D FOREIGN KEY (topic_id) REFERENCES topics (id) ON DELETE SET NULL NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE feedback_notes DROP CONSTRAINT FK_95BA3FE9CB944F1A');
        $this->addSql('ALTER TABLE feedback_notes DROP CONSTRAINT FK_95BA3FE9F675F31B');
        $this->addSql('ALTER TABLE feedback_notes DROP CONSTRAINT FK_95BA3FE91F55203D');
        $this->addSql('DROP TABLE feedback_notes');
    }
}
