<?php

declare(strict_types=1);

namespace App\Migrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260705115449 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE billing_transactions (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, reference VARCHAR(100) NOT NULL, amount_kobo INT NOT NULL, status VARCHAR(20) NOT NULL, channel VARCHAR(40) DEFAULT NULL, paid_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, institution_id INT NOT NULL, plan_id INT NOT NULL, initiated_by INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_5FFF51B9AEA34913 ON billing_transactions (reference)');
        $this->addSql('CREATE INDEX IDX_5FFF51B910405986 ON billing_transactions (institution_id)');
        $this->addSql('CREATE INDEX IDX_5FFF51B9E899029B ON billing_transactions (plan_id)');
        $this->addSql('CREATE INDEX IDX_5FFF51B9C28312E4 ON billing_transactions (initiated_by)');
        $this->addSql('CREATE TABLE subscription_plans (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, code VARCHAR(40) NOT NULL, name VARCHAR(100) NOT NULL, description TEXT DEFAULT NULL, price_kobo INT NOT NULL, interval VARCHAR(20) NOT NULL, max_students INT DEFAULT NULL, max_teachers INT DEFAULT NULL, features JSON DEFAULT NULL, is_active BOOLEAN DEFAULT true NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_CF5F99A277153098 ON subscription_plans (code)');
        $this->addSql('CREATE TABLE subscriptions (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, period_start TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, period_end TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, cancelled BOOLEAN DEFAULT false NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, institution_id INT NOT NULL, plan_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_4778A0110405986 ON subscriptions (institution_id)');
        $this->addSql('CREATE INDEX IDX_4778A01E899029B ON subscriptions (plan_id)');
        $this->addSql('ALTER TABLE billing_transactions ADD CONSTRAINT FK_5FFF51B910405986 FOREIGN KEY (institution_id) REFERENCES institutions (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE billing_transactions ADD CONSTRAINT FK_5FFF51B9E899029B FOREIGN KEY (plan_id) REFERENCES subscription_plans (id) ON DELETE RESTRICT NOT DEFERRABLE');
        $this->addSql('ALTER TABLE billing_transactions ADD CONSTRAINT FK_5FFF51B9C28312E4 FOREIGN KEY (initiated_by) REFERENCES users (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE subscriptions ADD CONSTRAINT FK_4778A0110405986 FOREIGN KEY (institution_id) REFERENCES institutions (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE subscriptions ADD CONSTRAINT FK_4778A01E899029B FOREIGN KEY (plan_id) REFERENCES subscription_plans (id) ON DELETE RESTRICT NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE billing_transactions DROP CONSTRAINT FK_5FFF51B910405986');
        $this->addSql('ALTER TABLE billing_transactions DROP CONSTRAINT FK_5FFF51B9E899029B');
        $this->addSql('ALTER TABLE billing_transactions DROP CONSTRAINT FK_5FFF51B9C28312E4');
        $this->addSql('ALTER TABLE subscriptions DROP CONSTRAINT FK_4778A0110405986');
        $this->addSql('ALTER TABLE subscriptions DROP CONSTRAINT FK_4778A01E899029B');
        $this->addSql('DROP TABLE billing_transactions');
        $this->addSql('DROP TABLE subscription_plans');
        $this->addSql('DROP TABLE subscriptions');
    }
}
