<?php

declare(strict_types=1);

namespace App\Migrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260705083311 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE guardian_links (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, relationship VARCHAR(40) DEFAULT \'parent\' NOT NULL, guardian_id INT NOT NULL, student_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_8FB5B0A311CC8B0A ON guardian_links (guardian_id)');
        $this->addSql('CREATE INDEX IDX_8FB5B0A3CB944F1A ON guardian_links (student_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_guardian_student ON guardian_links (guardian_id, student_id)');
        $this->addSql('ALTER TABLE guardian_links ADD CONSTRAINT FK_8FB5B0A311CC8B0A FOREIGN KEY (guardian_id) REFERENCES users (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE guardian_links ADD CONSTRAINT FK_8FB5B0A3CB944F1A FOREIGN KEY (student_id) REFERENCES users (id) ON DELETE CASCADE NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE guardian_links DROP CONSTRAINT FK_8FB5B0A311CC8B0A');
        $this->addSql('ALTER TABLE guardian_links DROP CONSTRAINT FK_8FB5B0A3CB944F1A');
        $this->addSql('DROP TABLE guardian_links');
    }
}
