<?php

declare(strict_types=1);

namespace App\Migrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260704214410 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE academic_sessions (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(50) NOT NULL, start_date DATE DEFAULT NULL, end_date DATE DEFAULT NULL, status VARCHAR(20) DEFAULT \'active\' NOT NULL, is_current BOOLEAN DEFAULT false NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, institution_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_A550150410405986 ON academic_sessions (institution_id)');
        $this->addSql('CREATE TABLE scheme_of_work (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, week_number SMALLINT NOT NULL, objective TEXT DEFAULT NULL, status VARCHAR(20) DEFAULT \'draft\' NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, class_id INT NOT NULL, subject_id INT NOT NULL, term_id INT DEFAULT NULL, topic_id INT DEFAULT NULL, assigned_teacher_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_2EA0ECC9EA000B10 ON scheme_of_work (class_id)');
        $this->addSql('CREATE INDEX IDX_2EA0ECC923EDC87 ON scheme_of_work (subject_id)');
        $this->addSql('CREATE INDEX IDX_2EA0ECC9E2C35FC ON scheme_of_work (term_id)');
        $this->addSql('CREATE INDEX IDX_2EA0ECC91F55203D ON scheme_of_work (topic_id)');
        $this->addSql('CREATE INDEX IDX_2EA0ECC979211D6C ON scheme_of_work (assigned_teacher_id)');
        $this->addSql('CREATE TABLE school_classes (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, level VARCHAR(50) NOT NULL, arm VARCHAR(30) DEFAULT NULL, status VARCHAR(20) DEFAULT \'active\' NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, institution_id INT NOT NULL, class_teacher_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_90C24C5D10405986 ON school_classes (institution_id)');
        $this->addSql('CREATE INDEX IDX_90C24C5DF78D8CBF ON school_classes (class_teacher_id)');
        $this->addSql('CREATE TABLE subjects (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(120) NOT NULL, code VARCHAR(30) DEFAULT NULL, curriculum_source VARCHAR(60) DEFAULT NULL, status VARCHAR(20) DEFAULT \'active\' NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, institution_id INT NOT NULL, class_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_AB25991710405986 ON subjects (institution_id)');
        $this->addSql('CREATE INDEX IDX_AB259917EA000B10 ON subjects (class_id)');
        $this->addSql('CREATE TABLE teacher_assignments (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, status VARCHAR(20) DEFAULT \'active\' NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, teacher_id INT NOT NULL, class_id INT NOT NULL, subject_id INT NOT NULL, term_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_E6D6EC9741807E1D ON teacher_assignments (teacher_id)');
        $this->addSql('CREATE INDEX IDX_E6D6EC97EA000B10 ON teacher_assignments (class_id)');
        $this->addSql('CREATE INDEX IDX_E6D6EC9723EDC87 ON teacher_assignments (subject_id)');
        $this->addSql('CREATE INDEX IDX_E6D6EC97E2C35FC ON teacher_assignments (term_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_teacher_class_subject_term ON teacher_assignments (teacher_id, class_id, subject_id, term_id)');
        $this->addSql('CREATE TABLE terms (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(50) NOT NULL, sequence SMALLINT DEFAULT 1 NOT NULL, start_date DATE DEFAULT NULL, end_date DATE DEFAULT NULL, status VARCHAR(20) DEFAULT \'active\' NOT NULL, is_current BOOLEAN DEFAULT false NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, session_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_88A23F71613FECDF ON terms (session_id)');
        $this->addSql('CREATE TABLE topic_delivery_packs (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, teacher_guide TEXT DEFAULT NULL, learner_note TEXT DEFAULT NULL, video_url VARCHAR(1024) DEFAULT NULL, worked_examples TEXT DEFAULT NULL, parent_wording TEXT DEFAULT NULL, status VARCHAR(20) DEFAULT \'draft\' NOT NULL, version VARCHAR(20) DEFAULT \'1.0\' NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, topic_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_CF04812D1F55203D ON topic_delivery_packs (topic_id)');
        $this->addSql('CREATE TABLE topics (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, week_number SMALLINT DEFAULT NULL, title VARCHAR(255) NOT NULL, strand VARCHAR(120) DEFAULT NULL, objective TEXT DEFAULT NULL, prerequisites TEXT DEFAULT NULL, core_theory TEXT DEFAULT NULL, misconceptions JSON DEFAULT NULL, question_types JSON DEFAULT NULL, real_life_relevance TEXT DEFAULT NULL, workplace_relevance TEXT DEFAULT NULL, competency_built TEXT DEFAULT NULL, portfolio_evidence_expected TEXT DEFAULT NULL, approval_status VARCHAR(20) DEFAULT \'draft\' NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, subject_id INT NOT NULL, class_id INT DEFAULT NULL, term_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_91F6463923EDC87 ON topics (subject_id)');
        $this->addSql('CREATE INDEX IDX_91F64639EA000B10 ON topics (class_id)');
        $this->addSql('CREATE INDEX IDX_91F64639E2C35FC ON topics (term_id)');
        $this->addSql('ALTER TABLE academic_sessions ADD CONSTRAINT FK_A550150410405986 FOREIGN KEY (institution_id) REFERENCES institutions (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE scheme_of_work ADD CONSTRAINT FK_2EA0ECC9EA000B10 FOREIGN KEY (class_id) REFERENCES school_classes (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE scheme_of_work ADD CONSTRAINT FK_2EA0ECC923EDC87 FOREIGN KEY (subject_id) REFERENCES subjects (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE scheme_of_work ADD CONSTRAINT FK_2EA0ECC9E2C35FC FOREIGN KEY (term_id) REFERENCES terms (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE scheme_of_work ADD CONSTRAINT FK_2EA0ECC91F55203D FOREIGN KEY (topic_id) REFERENCES topics (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE scheme_of_work ADD CONSTRAINT FK_2EA0ECC979211D6C FOREIGN KEY (assigned_teacher_id) REFERENCES users (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE school_classes ADD CONSTRAINT FK_90C24C5D10405986 FOREIGN KEY (institution_id) REFERENCES institutions (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE school_classes ADD CONSTRAINT FK_90C24C5DF78D8CBF FOREIGN KEY (class_teacher_id) REFERENCES users (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE subjects ADD CONSTRAINT FK_AB25991710405986 FOREIGN KEY (institution_id) REFERENCES institutions (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE subjects ADD CONSTRAINT FK_AB259917EA000B10 FOREIGN KEY (class_id) REFERENCES school_classes (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE teacher_assignments ADD CONSTRAINT FK_E6D6EC9741807E1D FOREIGN KEY (teacher_id) REFERENCES users (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE teacher_assignments ADD CONSTRAINT FK_E6D6EC97EA000B10 FOREIGN KEY (class_id) REFERENCES school_classes (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE teacher_assignments ADD CONSTRAINT FK_E6D6EC9723EDC87 FOREIGN KEY (subject_id) REFERENCES subjects (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE teacher_assignments ADD CONSTRAINT FK_E6D6EC97E2C35FC FOREIGN KEY (term_id) REFERENCES terms (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE terms ADD CONSTRAINT FK_88A23F71613FECDF FOREIGN KEY (session_id) REFERENCES academic_sessions (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE topic_delivery_packs ADD CONSTRAINT FK_CF04812D1F55203D FOREIGN KEY (topic_id) REFERENCES topics (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE topics ADD CONSTRAINT FK_91F6463923EDC87 FOREIGN KEY (subject_id) REFERENCES subjects (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE topics ADD CONSTRAINT FK_91F64639EA000B10 FOREIGN KEY (class_id) REFERENCES school_classes (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE topics ADD CONSTRAINT FK_91F64639E2C35FC FOREIGN KEY (term_id) REFERENCES terms (id) ON DELETE SET NULL NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE academic_sessions DROP CONSTRAINT FK_A550150410405986');
        $this->addSql('ALTER TABLE scheme_of_work DROP CONSTRAINT FK_2EA0ECC9EA000B10');
        $this->addSql('ALTER TABLE scheme_of_work DROP CONSTRAINT FK_2EA0ECC923EDC87');
        $this->addSql('ALTER TABLE scheme_of_work DROP CONSTRAINT FK_2EA0ECC9E2C35FC');
        $this->addSql('ALTER TABLE scheme_of_work DROP CONSTRAINT FK_2EA0ECC91F55203D');
        $this->addSql('ALTER TABLE scheme_of_work DROP CONSTRAINT FK_2EA0ECC979211D6C');
        $this->addSql('ALTER TABLE school_classes DROP CONSTRAINT FK_90C24C5D10405986');
        $this->addSql('ALTER TABLE school_classes DROP CONSTRAINT FK_90C24C5DF78D8CBF');
        $this->addSql('ALTER TABLE subjects DROP CONSTRAINT FK_AB25991710405986');
        $this->addSql('ALTER TABLE subjects DROP CONSTRAINT FK_AB259917EA000B10');
        $this->addSql('ALTER TABLE teacher_assignments DROP CONSTRAINT FK_E6D6EC9741807E1D');
        $this->addSql('ALTER TABLE teacher_assignments DROP CONSTRAINT FK_E6D6EC97EA000B10');
        $this->addSql('ALTER TABLE teacher_assignments DROP CONSTRAINT FK_E6D6EC9723EDC87');
        $this->addSql('ALTER TABLE teacher_assignments DROP CONSTRAINT FK_E6D6EC97E2C35FC');
        $this->addSql('ALTER TABLE terms DROP CONSTRAINT FK_88A23F71613FECDF');
        $this->addSql('ALTER TABLE topic_delivery_packs DROP CONSTRAINT FK_CF04812D1F55203D');
        $this->addSql('ALTER TABLE topics DROP CONSTRAINT FK_91F6463923EDC87');
        $this->addSql('ALTER TABLE topics DROP CONSTRAINT FK_91F64639EA000B10');
        $this->addSql('ALTER TABLE topics DROP CONSTRAINT FK_91F64639E2C35FC');
        $this->addSql('DROP TABLE academic_sessions');
        $this->addSql('DROP TABLE scheme_of_work');
        $this->addSql('DROP TABLE school_classes');
        $this->addSql('DROP TABLE subjects');
        $this->addSql('DROP TABLE teacher_assignments');
        $this->addSql('DROP TABLE terms');
        $this->addSql('DROP TABLE topic_delivery_packs');
        $this->addSql('DROP TABLE topics');
    }
}
