<?php

declare(strict_types=1);

namespace App\Migrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260705171340 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE interventions (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, reason TEXT NOT NULL, status VARCHAR(20) NOT NULL, due_date DATE DEFAULT NULL, outcome TEXT DEFAULT NULL, resolved_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, student_id INT NOT NULL, subject_id INT DEFAULT NULL, topic_id INT DEFAULT NULL, raised_by INT DEFAULT NULL, assigned_to INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_5ADBAD7FCB944F1A ON interventions (student_id)');
        $this->addSql('CREATE INDEX IDX_5ADBAD7F23EDC87 ON interventions (subject_id)');
        $this->addSql('CREATE INDEX IDX_5ADBAD7F1F55203D ON interventions (topic_id)');
        $this->addSql('CREATE INDEX IDX_5ADBAD7F4BE118D8 ON interventions (raised_by)');
        $this->addSql('CREATE INDEX IDX_5ADBAD7F89EEAF91 ON interventions (assigned_to)');
        $this->addSql('CREATE INDEX idx_intervention_status ON interventions (status)');
        $this->addSql('ALTER TABLE interventions ADD CONSTRAINT FK_5ADBAD7FCB944F1A FOREIGN KEY (student_id) REFERENCES users (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE interventions ADD CONSTRAINT FK_5ADBAD7F23EDC87 FOREIGN KEY (subject_id) REFERENCES subjects (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE interventions ADD CONSTRAINT FK_5ADBAD7F1F55203D FOREIGN KEY (topic_id) REFERENCES topics (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE interventions ADD CONSTRAINT FK_5ADBAD7F4BE118D8 FOREIGN KEY (raised_by) REFERENCES users (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE interventions ADD CONSTRAINT FK_5ADBAD7F89EEAF91 FOREIGN KEY (assigned_to) REFERENCES users (id) ON DELETE SET NULL NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE interventions DROP CONSTRAINT FK_5ADBAD7FCB944F1A');
        $this->addSql('ALTER TABLE interventions DROP CONSTRAINT FK_5ADBAD7F23EDC87');
        $this->addSql('ALTER TABLE interventions DROP CONSTRAINT FK_5ADBAD7F1F55203D');
        $this->addSql('ALTER TABLE interventions DROP CONSTRAINT FK_5ADBAD7F4BE118D8');
        $this->addSql('ALTER TABLE interventions DROP CONSTRAINT FK_5ADBAD7F89EEAF91');
        $this->addSql('DROP TABLE interventions');
    }
}
